const OPTION = {
  AUTHORIZATION_OPTIONS: ["No Auth", "API Key", "Bearer Token", "Basic Auth", "OAuth 2.0"],
  ADD_TO_OPTIONS: ["Headers", "Query Params"],
  OAUTH2_GRANT_TYPES: [
    "Authorization Code",
    "Authorization Code (with PKCE)",
    "Client Credentials",
  ],
  OAUTH2_TOKEN_TYPES: ["Access token", "ID token"],
  OAUTH2_PKCE_METHODS: ["SHA-256", "Plain"],
  OAUTH2_CLIENT_AUTH_OPTIONS: [
    "Send as Basic Auth header",
    "Send client credentials in body",
  ],
  REQUEST_METHOD_OPTIONS: ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"],
  REQUEST_MENU_OPTIONS: ["Params", "Auth", "Headers", "Body", "{ }"],
  REQUEST_BODY_RAW_OPTIONS: [
    { option: "Text", headerField: "text/plain" },
    { option: "JavaScript", headerField: "application/javascript" },
    { option: "JSON", headerField: "application/json" },
    { option: "HTML", headerField: "text/html" },
    { option: "XML", headerField: "application/xml" },
  ],
  REQUEST_BODY_OPTIONS: [
    { option: "None", headerField: "" },
    { option: "Form Data", headerField: "multipart/form-data" },
    { option: "Form Encoded", headerField: "application/x-www-form-urlencoded" },
    { option: "GraphQL", headerField: "application/json" },
    { option: "Raw", headerField: "text/plain" },
  ],
  RESPONSE_MENU_OPTIONS: ["Body", "Headers"],
  RESPONSE_BODY_OPTIONS: ["Pretty", "Raw", "Preview"],
  RESPONSE_RESULT_INFORMATION: ["Status", "Time", "Size"],
  RESPONSE_BODY_VIEW_FORMAT_OPTIONS: ["JSON", "HTML", "XML", "Text"],
  EDITOR_OPTIONS: {
    tabSize: 2,
    renderWhitespace: false,
    minimap: { enabled: false },
    scrollBeyondLastLine: false,
  },
  READ_ONLY_EDITOR_OPTIONS: {
    tabSize: 2,
    renderWhitespace: false,
    minimap: { enabled: false },
    scrollBeyondLastLine: false,
    readOnly: true,
  },
  EDITOR_DEFAULT_FONT_FAMILY: `"SF Mono", Monaco, Menlo, Consolas, "Ubuntu Mono", "Liberation Mono", "DejaVu Sans Mono", "Courier New", monospace`,
  READ_ONLY_TRUE_OPTION: { readOnly: true, lineNumbers: "on" },
  READ_ONLY_FALSE_OPTION: { readOnly: false, lineNumbers: "on" },
  LINE_NUMBER_OPTION: { readOnly: true, lineNumbers: "off" },
  CODE_SNIPPET_OPTIONS: [
    {
      key: "c",
      label: "C",
      editorLanguage: "c",
      variants: ["libcurl"],
    },
    {
      key: "csharp",
      label: "csharp",
      editorLanguage: "csharp",
      variants: ["HttpClient", "RestSharp"],
    },
    {
      key: "curl",
      label: "cURL",
      editorLanguage: "shell",
      variants: ["cURL"],
    },
    {
      key: "dart",
      label: "Dart",
      editorLanguage: "dart",
      variants: ["dio", "http"],
    },
    {
      key: "go",
      label: "Go",
      editorLanguage: "go",
      variants: ["Native"],
    },
    {
      key: "http",
      label: "HTTP",
      editorLanguage: "text",
      variants: ["HTTP"],
    },
    {
      key: "java",
      label: "Java",
      editorLanguage: "java",
      variants: ["OkHttp", "Unirest"],
    },
    {
      key: "javascript",
      label: "JavaScript",
      editorLanguage: "javascript",
      variants: ["Fetch", "jQuery", "XHR"],
    },
    {
      key: "kotlin",
      label: "Kotlin",
      editorLanguage: "kotlin",
      variants: ["Okhttp"],
    },
    {
      key: "nodejs",
      label: "NodeJs",
      editorLanguage: "javascript",
      variants: ["Axios", "Native", "Request", "Unirest"],
    },
    {
      key: "objective-c",
      label: "Objective-C",
      editorLanguage: "objective-c",
      variants: ["NSURLSession"],
    },
    {
      key: "ocaml",
      label: "OCaml",
      editorLanguage: "text",
      variants: ["Cohttp"],
    },
    {
      key: "php",
      label: "PHP",
      editorLanguage: "php",
      variants: ["cURL", "Guzzle", "HTTP_Request2", "pecl_http"],
    },
    {
      key: "powershell",
      label: "PowerShell",
      editorLanguage: "shell",
      variants: ["RestMethod"],
    },
    {
      key: "python",
      label: "Python",
      editorLanguage: "python",
      variants: ["http.client", "Requests"],
    },
    {
      key: "r",
      label: "R",
      editorLanguage: "r",
      variants: ["httr", "RCurl"],
    },
    {
      key: "ruby",
      label: "Ruby",
      editorLanguage: "ruby",
      variants: ["Net::HTTP"],
    },
    {
      key: "rust",
      label: "Rust",
      editorLanguage: "rust",
      variants: ["reqwest"],
    },
    {
      key: "shell",
      label: "Shell",
      editorLanguage: "shell",
      variants: ["Httpie", "wget"],
    },
    {
      key: "swift",
      label: "Swift",
      editorLanguage: "swift",
      variants: ["URLSession"],
    },
  ],
};

export default OPTION;
